steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/password-checker', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/password-checker']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'password-checker', '--image', 'gcr.io/$PROJECT_ID/password-checker', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']